### ISSUE TITLE
Coverage report files should be better organized

### ISSUE THREAD

**Issue by G0dwin** [lingua-franca/marmara#2]
Cover report files are currently dumped in the log directory using just the base name, this could cause collisions. We should probably put them in appropriate directories.

**Comment by G0dwin** [comment]
I think files should be placed by default in a folder based on where they were found. For example if the URI was `http://localhost:3000/assets/application-f566f2917d3cd874a6e97321c47cf09b332dd6344601f5d5fc6d77aa72343dd0.css`, then by default it should be placed in: `/logs/css/localhost-3000/assets/application-f566f2917d3cd874a6e97321c47cf09b332dd6344601f5d5fc6d77aa72343dd0.css.html`.

However, especially with long names like this we should let users define rules to change how files are named along with other config for that file:

```YAML
files:
  localhost:\d+/assets/application/(*)\-[\w\d]+:
    path: /local/\1
    coverage:
      rule: 50
      byte: 70
  googleapis:
    ignore: true
```

This config would allow us to ignore anything coming from `www.googleapis.com` (google fonts) and place our `application.css` report in `/log/css/local/application.css.html`.
