### ISSUE TITLE
Mark overridden rules as not covered

### ISSUE THREAD

**Issue by G0dwin** [lingua-franca/marmara#7]
If we have the following CSS rules:

```css
.myclass {
    display: block;
    background-color: red;
}

.myclass {
    background-color: blue;
}
```

Then we should mark then `background-color: red;` should be marked as not-covered.
