### ISSUE TITLE
Add a directive using comments to ignore a rule

### ISSUE THREAD

**Issue by G0dwin** [lingua-franca/marmara#9]
We should consider adding a way to ignore a rule if we determine that it is important but may never be reached during testing.  For example:

```css
/*
 * An example of how we could ignore a rule using comments
 */

/* define our primary body style */
body {
    width: 100%;
}

/** @MARMARA_IGNORE_START **/
/* fix our style for IE */
html.ie-9 body {
    min-width: 100%;
}
/** @MARMARA_IGNORE_END **/

/* style our header */
header {
    background-color: #444;
}
```

Using a syntax like this we could improve our overall coverage.
